In [24]:
import pandas as pd

df = pd.read_csv("employees.csv")
df[df.duplicated()]
df.duplicated().sum()

df[df.duplicated(keep=False)]
df.duplicated(subset=["name","department"]).sum()

df_clean = df.drop_duplicates(keep="last")
df_clean = df.drop_duplicates(keep=False)
df_clean

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,NaN,Pune,24-05-16,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-19,29,3.2,rahul.gupta@company.com
7,1008,Vivaan Chauhan,27.0,Female,HR,Associate,65792.0,Ahmedabad,25-10-22,3,3.5,vivaan.chauhan@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [27]:
"""
Q1: How many duplicate rows are in the employees DataFrame?
Q2: Display all the duplicate rows (including the first occurrence).
Q3: Remove duplicates keeping only the first occurrence and store in df_clean.
Q4: Check if there are employees with the same 'name' and 'email' (possible data entry errors)
"""
df.duplicated().sum()
df[df.duplicated(keep=False)]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-15,30,NaN,rohan.shah@company.com
6,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-24,12,2.8,karan.mishra@company.com
8,1009,Nikhil Patel,24.0,Female,Marketing,Senior,85452.0,Jaipur,14-01-17,1,4.2,nikhil.patel@company.com
480,1481,Aadhya Yadav,26.0,Female,Operations,Junior,30192.0,Kolkata,20-10-21,4,3.3,aadhya.yadav@company.com
484,1485,Varun Yadav,29.0,Male,Operations,Intern,21314.0,Pune,04-10-18,5,3.7,varun.yadav@company.com
487,1488,Ishaan Gupta,57.0,Male,Finance,Associate,52374.0,Mumbai,15-10-15,35,4.3,ishaan.gupta@company.com
490,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-25,9,4.8,ayaan.joshi@company.com
492,1493,Sai Kulkarni,39.0,Female,Product,Associate,48893.0,Chennai,13-08-21,19,2.7,sai.kulkarni@company.com
494,1495,Ritika Chauhan,27.0,Female,Product,Senior,74288.0,Ahmedabad,19-08-15,3,4.2,ritika.chauhan@company.com
505,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
506,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-15,30,NaN,rohan.shah@company.com
507,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-24,12,2.8,karan.mishra@company.com
508,1009,Nikhil Patel,24.0,Female,Marketing,Senior,85452.0,Jaipur,14-01-17,1,4.2,nikhil.patel@company.com
509,1481,Aadhya Yadav,26.0,Female,Operations,Junior,30192.0,Kolkata,20-10-21,4,3.3,aadhya.yadav@company.com
510,1485,Varun Yadav,29.0,Male,Operations,Intern,21314.0,Pune,04-10-18,5,3.7,varun.yadav@company.com
511,1488,Ishaan Gupta,57.0,Male,Finance,Associate,52374.0,Mumbai,15-10-15,35,4.3,ishaan.gupta@company.com
512,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-25,9,4.8,ayaan.joshi@company.com
513,1493,Sai Kulkarni,39.0,Female,Product,Associate,48893.0,Chennai,13-08-21,19,2.7,sai.kulkarni@company.com
514,1495,Ritika Chauhan,27.0,Female,Product,Senior,74288.0,Ahmedabad,19-08-15,3,4.2,ritika.chauhan@company.com