In [14]:
import pandas as pd

df = pd.read_csv("employees.csv")

# Selecting Rows by Position: iloc
df.iloc[0]
df.iloc[0:5]
df.iloc[[0,5,10]]

# Rows and Columns by position
df.iloc[0:3,0:4]
df.iloc[:,0:4]
df.iloc[0:3,:]
df.iloc[-3:]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [21]:
# Selecting rows by Label: loc
df.loc[0]
df.loc[0:5]

# Rows and Columns by label
df.loc[0:2,"name"]
df.loc[0:2,["name","salary"]]
df.loc[0:2,"name":"salary"]

            name   age  gender   department designation    salary
0   Kriti Saxena  33.0    Male  Engineering     Manager  133646.0
1    Aadhya Nair  39.0  Female  Engineering      Senior   81835.0
2  Bhavna Saxena  56.0    Male  Engineering      Intern   42051.0