In [2]:
import pandas as pd

df = pd.read_csv("employees.csv")

high_salary = df[df["salary"] > 100000]

df[df["department"] == "Engineering"]
df[df["department"] != "HR"]
df[df["age"] >= 40]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-15,30,NaN,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-19,29,3.2,rahul.gupta@company.com
14,1015,Ritika Reddy,42.0,Female,Product,Director,179122.0,Bangalore,29-07-22,22,NaN,ritika.reddy@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
487,1488,Ishaan Gupta,57.0,Male,Finance,Associate,52374.0,Mumbai,15-10-15,35,4.3,ishaan.gupta@company.com
488,1489,Priya Chopra,42.0,Female,Finance,Junior,33700.0,Ahmedabad,24-10-16,22,2.9,priya.chopra@company.com
493,1494,Suresh Verma,41.0,Female,Engineering,Senior,71811.0,Pune,10-11-17,20,2.6,suresh.verma@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com

In [3]:
# Filtering with Multiple Conditions
df[(df["department"] == "Engineering") & (df["salary"] > 100000)]
df[(df["city"] == "Mumbai") | (df["city"] == "Bangalore")]
df[(df["department"] == "Engineering") & (df["salary"] > 100000) & (df["age"] < 45)]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
23,1024,Rohan Rao,39.0,Female,Engineering,Lead,101199.0,Pune,27-07-23,19,2.9,rohan.rao@company.com
32,1033,Tanvi Iyer,22.0,Male,Engineering,Lead,101523.0,Jaipur,23-10-24,0,2.3,tanvi.iyer@company.com
62,1063,Vishal Tiwari,40.0,Male,Engineering,VP,202502.0,Jaipur,05-07-23,20,4.1,vishal.tiwari@company.com
64,1065,Swati Gupta,26.0,Male,Engineering,Manager,132742.0,Chennai,09-03-23,5,3.4,swati.gupta@company.com
78,1079,Amit Shah,42.0,Female,Engineering,Lead,110991.0,Ahmedabad,11-07-25,21,2.8,amit.shah@company.com
128,1129,Aditya Kulkarni,38.0,Male,Engineering,Manager,111742.0,Pune,13-11-18,15,2.8,aditya.kulkarni@company.com
143,1144,Tanya Kapoor,38.0,Female,Engineering,Manager,112642.0,Jaipur,17-02-15,16,3.6,tanya.kapoor@company.com
167,1168,Arun Kapoor,40.0,Male,Engineering,VP,207200.0,Ahmedabad,08-02-23,16,3.2,arun.kapoor@company.com
178,1179,Rakesh Bansal,38.0,Male,Engineering,Lead,108455.0,Kolkata,23-05-15,18,3.5,rakesh.bansal@company.com
184,1185,Siddharth Mishra,36.0,Male,Engineering,Manager,126753.0,Bangalore,06-01-23,12,NaN,siddharth.mishra@company.com
190,1191,Sneha Tiwari,31.0,Female,Engineering,Director,157674.0,Mumbai,28-03-16,10,3.5,sneha.tiwari@company.com
222,1223,Kunal Kulkarni,39.0,Male,Engineering,Director,154164.0,Mumbai,19-09-25,18,4.2,kunal.kulkarni@company.com
253,1254,Rakesh Chopra,44.0,Female,Engineering,Director,150869.0,Ahmedabad,28-11-15,20,2.8,rakesh.chopra@company.com
259,1260,Kavya Bhat,29.0,Female,Engineering,Director,175069.0,Ahmedabad,26-01-17,8,2.5,kavya.bhat@company.com
280,1281,Harsh Menon,38.0,Male,Engineering,Lead,105025.0,Surat,30-01-19,16,2.4,harsh.menon@company.com
286,1287,Suresh Reddy,37.0,Female,Engineering,Manager,120659.0,Delhi,28-03-22,15,3.3,suresh.reddy@company.com
329,1330,Gaurav Rao,39.0,Male,Engineering,Lead,100954.0,ahmedabad,14-03-16,17,2.2,gaurav.rao@company.com
344,1345,Arun Pillai,37.0,Male,Engineering,Manager,136489.0,Kolkata,11-03-22,15,4.4,arun.pillai@company.com
366,1367,Pallavi Pandey,22.0,Female,Engineering,Lead,102413.0,Surat,22-05-17,0,3.4,pallavi.pandey@company.com
400,1401,Rakesh Kumar,28.0,Male,Engineering,Lead,105929.0,Jaipur,30-04-24,5,2.5,rakesh.kumar@company.com
450,1451,Aryan Thakur,33.0,Female,Engineering,VP,215521.0,Kolkata,01-03-25,12,3.5,aryan.thakur@company.com
498,1499,Karan Mishra,37.0,Male,Engineering,VP,213644.0,Jaipur,24-10-15,13,2.9,karan.mishra@company.com

In [4]:
# Filtering with isin()
result = df[
    (df["city"] == "Mumbai") |
    (df["city"] == "Delhi") |
    (df["city"] == "Bangalore")
]
result = df[df["city"].isin(["Mumbai","Delhi","Bangalore"])]
result = df[~df["city"].isin(["Mumbai","Delhi","Bangalore"])]
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-19,29,3.2,rahul.gupta@company.com
7,1008,Vivaan Chauhan,27.0,Female,HR,Associate,65792.0,Ahmedabad,25-10-22,3,3.5,vivaan.chauhan@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
499,1500,Sandeep Patel,24.0,Female,NaN,Manager,110504.0,Hyderabad,01-03-23,1,2.5,sandeep.patel@company.com
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [5]:
# Filtering with between()
result = df[(df["age"] >= 25) & (df["age"] <= 35)]
result = df[df["age"].between(25,35)]
result = df[df["age"].between(25,35,inclusive="left")]
result = df[df["age"].between(25,35,inclusive="right")]
result = df[df["age"].between(25,35,inclusive="neither")]
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
7,1008,Vivaan Chauhan,27.0,Female,HR,Associate,65792.0,Ahmedabad,25-10-22,3,3.5,vivaan.chauhan@company.com
10,1011,Rohan Sharma,28.0,Female,Engineering,Lead,95758.0,Chennai,11-04-21,7,4.0,rohan.sharma@company.com
12,1013,Karan Saxena,30.0,Female,Support,Lead,101311.0,Jaipur,10-06-17,9,NaN,karan.saxena@company.com
24,1025,Shreya Mehta,31.0,Male,Sales,Junior,37291.0,Ahmedabad,23-03-23,10,3.0,shreya.mehta@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
490,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-25,9,4.8,ayaan.joshi@company.com
494,1495,Ritika Chauhan,27.0,Female,Product,Senior,74288.0,Ahmedabad,19-08-15,3,4.2,ritika.chauhan@company.com
497,1498,Kavya Mishra,28.0,Male,Operations,Senior,85288.0,Surat,30-12-17,5,NaN,kavya.mishra@company.com
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com

In [11]:
# Filtering with query()

# Standard Way (verbose way)
result = df[(df["department"] == "Engineering") & (df["salary"] > 80000)]

result = df.query("department == 'Engineering' and salary > 80000")
result = df.query("department != 'HR' and rating >= 4.0")

# What if we get values in a variable
min_salary = 100000
max_age = 40
department="HR"
result = df.query("salary > @min_salary and age < @max_age and department == @department")

result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
31,1032,Ayaan Chopra,35.0,Female,HR,Director,176500.0,Mumbai,28-10-25,14,3.7,ayaan.chopra@company.com
34,1035,Vihaan Verma,24.0,Female,HR,Lead,104333.0,Kolkata,21-12-19,4,2.9,vihaan.verma@company.com
115,1116,Varun Thakur,38.0,Male,HR,Lead,101346.0,Hyderabad,08-04-19,18,4.4,varun.thakur@company.com
261,1262,Ishaan Pandey,26.0,Male,HR,Director,173248.0,Pune,03-06-23,3,2.9,ishaan.pandey@company.com
273,1274,Pranav Gupta,23.0,Male,HR,Lead,112172.0,Delhi,13-09-20,3,2.3,pranav.gupta@company.com
310,1311,Deepak Iyer,25.0,Male,HR,Manager,117296.0,Mumbai,06-01-18,5,3.9,deepak.iyer@company.com
351,1352,Yash Bansal,38.0,Female,HR,Manager,135142.0,Bangalore,25-05-15,16,4.0,yash.bansal@company.com
473,1474,Vivaan Pillai,29.0,Female,HR,Director,175924.0,Bangalore,22-05-18,6,2.2,vivaan.pillai@company.com

In [22]:
# Filtering String Columns
result = df[df["name"].str.contains("Sharma")] # Case Sensitive
result = df[df["name"].str.contains("sharma" ,case=False)] # Case In-sensitive


result = df[df["name"].str.startswith("A")]
result = df[df["name"].str.len() > 15]
result = df[(df["name"].str.contains("Kumar",case=False)) & (df["department"] == "Engineering")]
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
98,1099,Dev Kumar,26.0,Male,Engineering,Intern,22162.0,Chennai,02-05-23,5,2.6,dev.kumar@company.com
146,1147,Diya Kumar,40.0,Female,Engineering,Senior,87793.0,Kolkata,06-06-20,16,4.3,diya.kumar@company.com
331,1332,Kabir Kumar,32.0,Female,Engineering,Senior,86443.0,Chennai,19-11-18,10,2.8,kabir.kumar@company.com
400,1401,Rakesh Kumar,28.0,Male,Engineering,Lead,105929.0,Jaipur,30-04-24,5,2.5,rakesh.kumar@company.com
421,1422,Vandana Kumar,46.0,Female,Engineering,Senior,91312.0,Surat,01-02-17,26,3.8,vandana.kumar@company.com