In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv("employees.csv")
df["city"] = df["city"].str.strip().str.title()
df["department"] = df["department"].str.strip().str.title()
df["salary"] = df["salary"].replace(-999, np.nan)
df = df.drop_duplicates()

# Sales (3 years of monthly data: product x region x month)
sales = pd.read_csv("monthly_sales.csv")
sales["date"] = pd.to_datetime(sales["date"])

sales

          date   product region  quantity  unit_price    revenue
0   2023-01-01    Laptop  North      47.0       54797  2575459.0
1   2023-01-01    Laptop  North      50.0       54797  2575459.0
2   2023-01-01    Laptop  South      34.0       54782  1862588.0
3   2023-01-01    Laptop   East      35.0       55457  1940995.0
4   2023-01-01    Laptop   West      61.0       55147  3363967.0
..         ...       ...    ...       ...         ...        ...
716 2025-12-01  Keyboard   West     164.0        2476   406064.0
717 2025-12-01   Headset  North     101.0        3242   327442.0
718 2025-12-01   Headset  South     136.0        3935   535160.0
719 2025-12-01   Headset   East     101.0        3499   353399.0
720 2025-12-01   Headset   West      95.0        3251   308845.0

[721 rows x 6 columns]

In [ ]:
jan = sales[sales["date"] == "2023-01-01"]
wide_jan_data=jan.pivot(index="product",columns="region",values="quantity")
wide_jan_data

ValueError: Index contains duplicate entries, cannot reshape

pivot_table

In [17]:
result=sales.pivot_table(index="product",columns="region",values=["quantity","revenue"],aggfunc=["sum","mean"])
result

              sum                                                    \
         quantity                              revenue
region       East   North   South    West         East        North
product
Headset    4032.0  3508.0  4059.0  3909.0   14017378.0   13362586.0
Keyboard   5555.0  5534.0  5625.0  5590.0   14130996.0   13984216.0
Laptop     2063.0  2258.0  2006.0  2170.0  115429948.0  117619400.0
Monitor    3071.0  3171.0  3155.0  3153.0   54107671.0   56989234.0
Mouse      7484.0  7539.0  6813.0  7300.0    5708906.0    6453853.0

                                          mean                          \
                                      quantity
region          South         West        East       North       South
product
Headset    14613118.0   13368569.0  112.000000  106.303030  112.750000
Keyboard   13696985.0   14034972.0  154.305556  158.114286  156.250000
Laptop    103345942.0  115615577.0   58.942857   61.027027   55.722222
Monitor    56670955.0   56849346.0   85.305556   90.600000   87.638889
Mouse       5706625.0    5845902.0  207.888889  209.416667  206.454545


                           revenue
region          West          East         North         South          West
product
Headset   108.583333  3.893716e+05  3.711829e+05  4.059199e+05  3.713491e+05
Keyboard  155.277778  3.925277e+05  3.995490e+05  3.804718e+05  4.009992e+05
Laptop     60.277778  3.206387e+06  3.360554e+06  3.039587e+06  3.303302e+06
Monitor    87.583333  1.545933e+06  1.628264e+06  1.574193e+06  1.579148e+06
Mouse     208.571429  1.585807e+05  1.792737e+05  1.585174e+05  1.670258e+05

In [20]:
result=sales.pivot_table(index="product",columns="region",values="revenue",aggfunc="sum",margins=True,margins_name="Total")
result

region           East        North        South         West        Total
product
Headset    14017378.0   13362586.0   14613118.0   13368569.0   55361651.0
Keyboard   14130996.0   13984216.0   13696985.0   14034972.0   55847169.0
Laptop    115429948.0  117619400.0  103345942.0  115615577.0  452010867.0
Monitor    54107671.0   56989234.0   56670955.0   56849346.0  224617206.0
Mouse       5708906.0    6453853.0    5706625.0    5845902.0   23715286.0
Total     203394899.0  208409289.0  194033625.0  205714366.0  811552179.0