In [6]:
import pandas as pd
import numpy as np

sales = pd.read_csv("monthly_sales.csv")
sales["date"] = pd.to_datetime(sales["date"])

df = pd.read_csv("employees.csv")
df["city"] = df["city"].str.strip().str.title()
df["department"] = df["department"].str.strip().str.title()
df["salary"] = df["salary"].replace(-999, np.nan)
df = df.drop_duplicates()

result=pd.crosstab(df["department"],df["gender"],margins=True,margins_name="Total")
result

gender       Female  Male  Total
department
Engineering      67    69    136
Finance          19    27     46
Hr               23    22     45
Marketing        19    31     50
Operations       23    21     44
Product          25    41     66
Sales            28    41     69
Support          22    19     41
Total           226   271    497

In [16]:
result=pd.crosstab(df["department"],df["gender"],normalize="all")*100
result=pd.crosstab(df["department"],df["gender"],normalize="index")*100
result

gender          Female       Male
department
Engineering  49.264706  50.735294
Finance      41.304348  58.695652
Hr           51.111111  48.888889
Marketing    38.000000  62.000000
Operations   52.272727  47.727273
Product      37.878788  62.121212
Sales        40.579710  59.420290
Support      53.658537  46.341463

In [22]:
result=pd.crosstab(df["department"],df["gender"],values=df["salary"],aggfunc="max")
result

gender         Female      Male
department
Engineering  215521.0  213644.0
Finance      209488.0  216829.0
Hr           215185.0  173248.0
Marketing    200896.0  213688.0
Operations   218890.0  112964.0
Product      179122.0  209477.0
Sales        218345.0  216954.0
Support      111049.0  214690.0

In [26]:
result=pd.crosstab([df["department"],df["designation"]],df["gender"],values=df["salary"],aggfunc="mean")
result

gender                          Female           Male
department  designation
Engineering Associate     60484.000000   57112.357143
            Director     166808.833333  158598.000000
            Intern        34581.000000   29537.200000
            Junior        52769.909091   38841.857143
            Lead          99412.600000  100889.500000
...                                ...            ...
Support     Junior        37967.000000   39622.000000
            Lead         103182.500000  114084.000000
            Manager                NaN  133220.750000
            Senior        80492.750000   87616.000000
            VP                     NaN  214690.000000

[64 rows x 2 columns]