In [5]:
import pandas as pd
import numpy as np

employees = pd.read_csv("employees.csv")
departments = pd.read_csv("departments.csv")
projects = pd.read_csv("projects.csv")
emp_projects = pd.read_csv("employee_projects.csv")

# Practical example: merge emp_projects with BOTH employees AND projects
step1 = pd.merge(emp_projects,employees[["emp_id","name","department"]],on="emp_id")
final = pd.merge(step1,projects[["project_id","project_name","status"]])
final

,emp_id,project_id,role,hours_per_week,name,department,project_name,status
0,1393,2016,Analyst,27,Dhruv Mehta,Marketing,Help Desk AI,On Hold
1,1309,2019,Lead,23,Riya Menon,Engineering,Content Platform,Completed
2,1309,2011,Lead,20,Riya Menon,Engineering,Social Media Analytics,Active
3,1305,2018,Analyst,31,Dev Kulkarni,Finance,Lead Scoring,Completed
4,1286,2018,Lead,10,Ayaan Saxena,Finance,Lead Scoring,Completed
...,...,...,...,...,...,...,...,...
590,1185,2003,Developer,37,Siddharth Mishra,Engineering,Brand Campaign Q1,Completed
591,1467,2019,Lead,6,Suresh Singh,Engineering,Content Platform,Completed
592,1042,2003,Lead,31,Aadhya Joshi,Product,Brand Campaign Q1,Completed
593,1042,2001,Tester,26,Aadhya Joshi,Product,Data Pipeline v2,Planning
594,1042,2020,Developer,39,Aadhya Joshi,Product,Compliance Audit,On Hold

Handling Duplicate Column Names

In [8]:
result = pd.merge(projects, departments, on="dept_id",suffixes=("_product","_department"))
result

,project_id,project_name,dept_id,start_date,end_date,status,budget_lakhs_product,dept_name,dept_head,budget_lakhs_department,location
0,2001,Data Pipeline v2,107,2024-01-01,2024-02-25,Planning,88,Product,Karan Joshi,280,Bangalore
1,2002,CRM Upgrade,103,2024-01-16,2024-05-11,Active,15,Marketing,Amit Verma,250,Mumbai
2,2003,Brand Campaign Q1,102,2024-01-31,2024-06-01,Completed,42,Sales,Sunita Sharma,300,Mumbai
3,2004,Employee Portal,107,2024-02-15,2024-06-25,Completed,64,Product,Karan Joshi,280,Bangalore
4,2005,Budget Forecasting,105,2024-03-01,2024-06-09,Active,28,Finance,Vikram Mehta,400,Mumbai
5,2006,Warehouse Automation,108,2024-03-16,2024-09-01,On Hold,86,Support,Neha Gupta,180,Pune
6,2007,Mobile App Redesign,106,2024-03-31,2024-08-02,On Hold,38,Operations,Deepa Reddy,350,Hyderabad
7,2008,Chatbot v3,108,2024-04-15,2024-09-09,Completed,70,Support,Neha Gupta,180,Pune
8,2009,API Gateway,101,2024-04-30,2024-10-24,Active,79,Engineering,Rajiv Kapoor,500,Bangalore
9,2010,Sales Dashboard,101,2024-05-15,2024-10-10,Active,88,Engineering,Rajiv Kapoor,500,Bangalore
10,2011,Social Media Analytics,103,2024-05-30,2024-08-18,Active,89,Marketing,Amit Verma,250,Mumbai
11,2012,Payroll System,107,2024-06-14,2024-10-02,On Hold,33,Product,Karan Joshi,280,Bangalore
12,2013,Cost Optimization,103,2024-06-29,2024-09-02,Active,32,Marketing,Amit Verma,250,Mumbai
13,2014,Supply Chain Tracker,104,2024-07-14,2024-10-18,On Hold,19,HR,Priya Nair,150,Delhi
14,2015,Feature Flagging,105,2024-07-29,2025-01-03,Completed,63,Finance,Vikram Mehta,400,Mumbai
15,2016,Help Desk AI,106,2024-08-13,2025-01-03,On Hold,50,Operations,Deepa Reddy,350,Hyderabad
16,2017,Cloud Migration,103,2024-08-28,2025-01-15,Completed,58,Marketing,Amit Verma,250,Mumbai
17,2018,Lead Scoring,104,2024-09-12,2025-03-02,Completed,26,HR,Priya Nair,150,Delhi
18,2019,Content Platform,107,2024-09-27,2025-02-03,Completed,65,Product,Karan Joshi,280,Bangalore
19,2020,Compliance Audit,105,2024-10-12,2025-02-27,On Hold,54,Finance,Vikram Mehta,400,Mumbai