In [2]:
import pandas as pd
import numpy as np

employees = pd.read_csv("employees.csv")
departments = pd.read_csv("departments.csv")
projects = pd.read_csv("projects.csv")
emp_projects = pd.read_csv("employee_projects.csv")

first_half = employees.iloc[:250]
second_half = employees.iloc[250:]

# Vertical Concat (stack rows)
combined=pd.concat([first_half,second_half],ignore_index=True)
combined

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-15,30,NaN,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [7]:
df1 = pd.DataFrame({"name": ["Alice"], "age": [30], "city": ["Mumbai"]})
df2 = pd.DataFrame({"name": ["Bob"], "salary": [50000], "dept": ["Sales"]})

result = pd.concat([df1,df2],ignore_index=True,join="inner")
result

    name
0  Alice
1    Bob