In [2]:
import pandas as pd

df = pd.read_csv("employees.csv")
df["salary"]=df["salary"].fillna(0).astype(int)
df["annual_salary"] = df["salary"] * 12
df["tax"] = df["salary"] * 0.3
df["in_hand_salary"] = df["salary"] - df["tax"]
df[["salary","tax","in_hand_salary","annual_salary"]]

     salary      tax  in_hand_salary  annual_salary
0     32153   9645.9         22507.1         385836
1         0      0.0             0.0              0
2     32123   9636.9         22486.1         385476
3     72798  21839.4         50958.6         873576
4     91113  27333.9         63779.1        1093356
..      ...      ...             ...            ...
510   21314   6394.2         14919.8         255768
511   52374  15712.2         36661.8         628488
512   80129  24038.7         56090.3         961548
513   48893  14667.9         34225.1         586716
514   74288  22286.4         52001.6         891456

[515 rows x 4 columns]

In [3]:
import numpy as np

df["is_senior"]=np.where(df['experience_years']>=20,"Yes","No")

conditions=[df["salary"]>=140000,
            df["salary"]>=70000,
            df["salary"]<70000]
choices=["High","Medium","Low"]

df["salary_category"]=np.select(conditions,choices,"Unknown")

df[["experience_years","is_senior","salary","salary_category"]]

     experience_years is_senior  salary salary_category
0                  10        No   32153             Low
1                  15        No       0             Low
2                  34       Yes   32123             Low
3                  30       Yes   72798          Medium
4                  24       Yes   91113          Medium
..                ...       ...     ...             ...
510                 5        No   21314             Low
511                35       Yes   52374             Low
512                 9        No   80129          Medium
513                19        No   48893             Low
514                 3        No   74288          Medium

[515 rows x 4 columns]

In [9]:
# Removing Columns
# df=df.drop(columns=["email"])
# df=df[df["salary"] > 50000]

df.insert(2,"full_name",df["name"])
df

,emp_id,name,full_name,age,gender,department,designation,salary,City,join_date,experience_years,ratiNG,annual_salary,tax,in_hand_salary,is_senior,salary_category
0,1001,Kriti Saxena,Kriti Saxena,33.0,Male,Engineering,Manager,32153,Delhi,25-04-24,10,3.5,385836,9645.9,22507.1,No,Low
1,1002,Aadhya nair,Aadhya nair,NaN,Female,Engineering,Senior,0,Pune,24-05-16,15,NaN,0,0.0,0.0,No,Low
2,1003,BhavNA saxena,BhavNA saxena,56.0,Male,Engineering,Intern,32123,Pune,28-06-17,34,4.3,385476,9636.9,22486.1,Yes,Low
3,1004,ROHhan Shah,ROHhan Shah,51.0,Male,Sales,Associate,72798,Mumbai,11-03-15,30,NaN,873576,21839.4,50958.6,Yes,Medium
4,1005,Geeta Nair,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,27333.9,63779.1,Yes,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,1485,Varun Yadav,Varun Yadav,29.0,Male,Operations,Intern,21314,Pune,04-10-18,5,3.7,255768,6394.2,14919.8,No,Low
511,1488,Ishaan Gupta,Ishaan Gupta,57.0,Male,Finance,Associate,52374,Mumbai,15-10-15,35,4.3,628488,15712.2,36661.8,Yes,Low
512,1491,Ayaan Joshi,Ayaan Joshi,30.0,Male,Engineering,Senior,80129,Chennai,30-09-25,9,4.8,961548,24038.7,56090.3,No,Medium
513,1493,Sai Kulkarni,Sai Kulkarni,39.0,Female,Product,Associate,48893,Chennai,13-08-21,19,2.7,586716,14667.9,34225.1,No,Low
514,1495,Ritika Chauhan,Ritika Chauhan,27.0,Female,Product,Senior,74288,Ahmedabad,19-08-15,3,4.2,891456,22286.4,52001.6,No,Medium