In [6]:
import pandas as pd
import numpy as np

def salary_category(salary):
    if salary>=120000:
        return "High"
    elif salary >= 70000:
        return "Medium"
    else:
        return "Low"
    
def summary(row):
    return f"Name is {row['name']} and salary is {row['salary']}"


df = pd.read_csv("employees.csv")
df["salary_category"]=df["salary"].apply(salary_category)
df["last_name"]=df["name"].apply(lambda x:x.split()[-1])

df["summary"]=df.apply(summary,axis=1)

df[["salary","salary_category","name","last_name","summary"]]

,salary,salary_category,name,last_name,summary
0,32153.0,Low,Kriti Saxena,Saxena,Name is Kriti Saxena and salary is 32153.0
1,NaN,Low,Aadhya nair,nair,Name is Aadhya nair and salary is nan
2,32123.0,Low,BhavNA saxena,saxena,Name is BhavNA saxena and salary is 32123.0
3,72798.0,Medium,ROHhan Shah,Shah,Name is ROHhan Shah and salary is 72798.0
4,91113.0,Medium,Geeta Nair,Nair,Name is Geeta Nair and salary is 91113.0
...,...,...,...,...,...
510,21314.0,Low,Varun Yadav,Yadav,Name is Varun Yadav and salary is 21314.0
511,52374.0,Low,Ishaan Gupta,Gupta,Name is Ishaan Gupta and salary is 52374.0
512,80129.0,Medium,Ayaan Joshi,Joshi,Name is Ayaan Joshi and salary is 80129.0
513,48893.0,Low,Sai Kulkarni,Kulkarni,Name is Sai Kulkarni and salary is 48893.0
514,74288.0,Medium,Ritika Chauhan,Chauhan,Name is Ritika Chauhan and salary is 74288.0

In [23]:
df["bonus_eligible"]=df["ratiNG"].apply(lambda x:"Yes" if x>4.0 else "No")
df[["ratiNG","bonus_eligible"]]


"""
Date parts:

%d → day (01, 15, 31)
%m → month as number (01, 12)
%b → month abbreviated (Jan, Feb)
%B → month full (January, February)
%Y → 4-digit year (2024)
%y → 2-digit year (24)

Time parts:

%H → hour 24hr (00-23)
%I → hour 12hr (01-12)
%M → minute (00-59)
%S → second (00-59)
%p → AM/PM
"""
df["join_date"]=pd.to_datetime(df["join_date"],format="mixed")
df["days_since_joining"] = df["join_date"].apply(lambda x:(pd.Timestamp.now()-x).days)
df["years_since_joining"] = df["join_date"].apply(lambda x:(pd.Timestamp.now()-x).days//365)
df[["join_date","days_since_joining","years_since_joining"]]

     join_date  days_since_joining  years_since_joining
0   2024-04-25                 713                    1
1   2016-05-24                3606                    9
2   2017-06-28                3206                    8
3   2015-11-03                3809                   10
4   2021-04-03                1831                    5
..         ...                 ...                  ...
510 2018-04-10                2920                    8
511 2015-10-15                3828                   10
512 2025-09-30                 190                    0
513 2021-08-13                1699                    4
514 2015-08-19                3885                   10

[515 rows x 3 columns]